#!/bin/sh
# HG680P di belakang modem rumah (192.168.101.0/24): ambil IP dari modem, jangan jadi DHCP server.
uci set network.lan.proto='dhcp'
uci -q delete network.lan.ipaddr
uci -q delete network.lan.netmask
uci set dhcp.lan.ignore='1'
# Jangan jadi router/DNS IPv6 di jaringan rumah (RA/DHCPv6 sempat membuat laptop memakai STB sebagai DNS)
uci set dhcp.lan.ra='disabled'
uci set dhcp.lan.dhcpv6='disabled'
uci set dhcp.lan.ndp='disabled'
uci set network.globals.ula_prefix=''

# IP cadangan permanen untuk colok langsung ke laptop tanpa DHCP: ssh root@169.254.1.2
uci set network.lan_fallback='interface'
uci set network.lan_fallback.proto='static'
uci set network.lan_fallback.device='br-lan'
uci set network.lan_fallback.ipaddr='169.254.1.2'
uci set network.lan_fallback.netmask='255.255.0.0'
uci add_list firewall.@zone[0].network='lan_fallback'

# Tailscale: exit node + subnet router keluar lewat lan
uci set network.tailscale='interface'
uci set network.tailscale.proto='none'
uci set network.tailscale.device='tailscale0'
uci set firewall.tailscale='zone'
uci set firewall.tailscale.name='tailscale'
uci set firewall.tailscale.network='tailscale'
uci set firewall.tailscale.input='ACCEPT'
uci set firewall.tailscale.output='ACCEPT'
uci set firewall.tailscale.forward='ACCEPT'
uci set firewall.ts_lan='forwarding'
uci set firewall.ts_lan.src='tailscale'
uci set firewall.ts_lan.dest='lan'
uci set firewall.@zone[0].masq='1'   # zona lan: lalu lintas dari tailscale keluar pakai IP STB

# watchcat: internet putus 5 menit -> restart lan, 30 menit -> reboot
while uci -q delete watchcat.@watchcat[0]; do :; done
uci add watchcat watchcat
uci set watchcat.@watchcat[-1].mode='restart_iface'
uci set watchcat.@watchcat[-1].interface='lan'
uci set watchcat.@watchcat[-1].period='5m'
uci set watchcat.@watchcat[-1].pinghosts='1.1.1.1 8.8.8.8'
uci add watchcat watchcat
uci set watchcat.@watchcat[-1].mode='ping_reboot'
uci set watchcat.@watchcat[-1].period='30m'
uci set watchcat.@watchcat[-1].forcedelay='1m'
uci set watchcat.@watchcat[-1].pinghosts='1.1.1.1 8.8.8.8'

uci commit
exit 0
